<Project>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591;SA1028;SA1101;SA1200;SA1201;SA1202;SA1204;SA1208;SA1210;SA1309;SA1316;SA1402;SA1413;SA1501;SA1503;SA1507;SA1513;SA1515;SA1516;SA1519;SA1600;SA1602;SA1611;SA1615;SA1618;SA1623;SA1629;SA1633;SA1634;SA1649;SA1116;SA1117;SA1122;SA1128</NoWarn>
  </PropertyGroup>
</Project>
